export const allProducts = [
  {
    id: 1,
    name: "ComfortNest Single Bed",
    description: "A cozy single bed for a perfect night's sleep.",
    price: 21500,
    category: "Beds",
    Subcategory: "Single Beds",
    image: "https://api.bedwoodfurnishing.com/17289681602860.2792287751433504.jpeg",
    availableColors: ["Brown", "White", "Walnut"],
  },
  {
    id: 2,
    name: "UrbanStyle Single Bed",
    description: "Modern design single bed that fits any room.",
    price: 19999,
    category: "Beds",
    Subcategory: "Single Beds",
    image: "https://api.bedwoodfurnishing.com/17287353366860.22907565879176595.jpeg",
    availableColors: ["Brown", "White", "Walnut"],
  },
  {
    id: 3,
    name: "RusticWood Single Bed",
    description: "Crafted from solid wood, adding rustic charm.",
    price: 18500,
    category: "Beds",
    Subcategory: "Single Beds",
    image: "https://api.bedwoodfurnishing.com/17287357225530.33504715990526424.jpeg",
    availableColors: ["Brown", "White", "Walnut"],
  },
  {
    id: 4,
    name: "SpaceSaver Single Bed",
    description: "Compact design with under-bed storage.",
    price: 22500,
    category: "Beds",
    Subcategory: "Single Beds",
    image: "https://api.bedwoodfurnishing.com/17287354411230.8002171937314717.jpeg",
    availableColors: ["Brown", "White", "Walnut"],
  },
  {
    id: 11,
    name: "Storage Ottoman Bed",
    description: "The Storage Ottoman Bed provides a space-saving solution for small bedrooms.",
    price: 7000,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "/double-bed/db1.jpeg",
    availableColors: ["Brown", "White", "Walnut"],
  },
  {
    id: 12,
    name: "Rustic Wooden Bed",
    description: "The Rustic Wooden Bed brings natural charm to your bedroom with its solid wood construction.",
    price: 8000,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "/double-bed/db2.jpeg",
    availableColors: ["White", "Grey"],
  },
  {
    id: 13,
    name: "Serenity Queen Bed",
    description: "The Serenity Queen Bed features a stylish upholstered headboard with a soft fabric finish.",
    price: 9000,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "/double-bed/db3.jpeg",
    availableColors: ["White"],
  },
  {
    id: 14,
    name: "Luxury Tufted Bed",
    description: "The Luxury Tufted Bed adds an opulent touch to any bedroom with its deeply tufted headboard.",
    price: 9000,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "/double-bed/db4.jpeg",
    availableColors: ["Grey", "White"],
  },
  {
    id: 15,
    name: "Adjustable Comfort Bed",
    description: "The Adjustable Comfort Bed provides personalized sleep positions with its motorized base.",
    price: 9000,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "https://api.bedwoodfurnishing.com/17287158191620.28202327157655493.jpeg",
    availableColors: ["Blue", "Grey"],
  },
  {
    id: 16,
    name: "Rustic Charm Queen Bed",
    description: "Crafted from reclaimed wood, the Rustic Charm Queen Bed showcases a beautiful distressed finish.",
    price: 9800,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "/double-bed/db5.jpeg",
    availableColors: ["Grey"],
  },
  {
    id: 17,
    name: "Luxury Pillow-Top Bed",
    description: "The Luxury Pillow-Top Bed offers unparalleled comfort with its plush, pillow-top mattress design.",
    price: 9900,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "/double-bed/db6.jpeg",
    availableColors: ["Wooden", "White"],
  },
  {
    id: 18,
    name: "Luxury Bed",
    description: "Experience ultimate comfort and style with our Comfort Lux King Size Bed.",
    price: 10000,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "/double-bed/db7.jpeg",
    availableColors: ["Brown"],
  },
  {
    id: 19,
    name: "EliteSleep Storage Double Bed",
    description: "The EliteSleep double bed offers modern functionality with built-in storage drawers underneath.",
    price: 11000,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "/double-bed/db9.jpeg",
    availableColors: ["Brown"],
  },
  {
    id: 20,
    name: "NatureNest Wooden Platform Double Bed",
    description: "Crafted from eco-friendly solid wood, the NatureNest is a platform-style double bed.",
    price: 13000,
    category: "Beds",
    Subcategory: "Double Beds",
    image: "https://api.bedwoodfurnishing.com/17287361361190.4702337834221135.jpeg",
    availableColors: ["Brown"],
  },
  {
    id: 21,
    name: "Pepperfry McCoy Solid Wood Sofa",
    description: "Made from premium mango wood, the McCoy sofa features a stylish mid-century modern design.",
    price: 5000,
    category: "Furniture",
    Subcategory: "Living Sofa",
    image: "https://api.bedwoodfurnishing.com/17288839229900.5548855120322551.jpeg",
    availableColors: ["Pink"],
  },
  {
    id: 22,
    name: "Modern Sectional Sofa",
    description: "This 2-seater sofa is made of high-quality engineered wood with a slatted backrest.",
    price: 5000,
    category: "Furniture",
    Subcategory: "Living Sofa",
    image: "https://api.bedwoodfurnishing.com/17288837176780.0047299705261940606.jpeg",
    availableColors: ["Black"],
  },
  {
    id: 23,
    name: "Handcrafted Mango Wood Sofa",
    description: "The Handcrafted Mango Wood Sofa showcases exquisite craftsmanship with its natural, eco-friendly frame.",
    price: 6000,
    category: "Furniture",
    Subcategory: "Living Sofa",
    image: "https://api.bedwoodfurnishing.com/17287271744420.05446565417746574.jpeg",
    availableColors: ["Black"],
  },
];
localStorage.setItem("allProducts", JSON.stringify(allProducts));
